import { convertToEn, convertToFa } from './Utilities';
import DtCalendar from './DtCalendar';
import DtPicker from './DtPicker';
import { IDay, IRange } from './type';
declare type Day = IDay | null;
declare type Range = IRange | null;
declare type Multi = IDay[] | null;
export { DtCalendar, convertToEn, convertToFa };
export type { Day, Range, Multi };
export default DtPicker;
